spring.application.name=Boot_FinalProj-1
server.port=${PORT:8080}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/12sep25jee
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

brevo.api.key=${bskPUA6Na5cIZdJ}
mail.from=${solankiayush645@gmail.com}